vbd/dashboard/urls.py
'''
Created on Jun 28, 2017

@author: xieyanyang
'''

from django.conf.urls import url

from dashboard import views, op_views, result_views


urlpatterns = [
    # Examples:
    #url(r'^$', 'dashboard.views.home', name='home'),
    
    # settings --> globalSettings
    url(r'^settings/global$', views.global_settings, name='global_settings'),
    url(r'^settings/kubernetes$', views.kubernetes_settings, name='kubernetes_settings'),
    
    # Basic Environment setting Home
    url(r'^env_setting$', op_views.env_setting, name='env_setting'),
    
    # Components status and operation
    url(r'^op/status$', op_views.fetch_component_status, name='fetch_compontent_status'),
    url(r'^op/execute$', op_views.execute_cmd, name='execute_cmd'),
    url(r'^op/update$', op_views.update_benchmark_config, name='update_benchmark_config'),
    
    
    # Benchmark operation Home
    url(r'^bop$', op_views.benchmark_operation, name='benchmark_operation'),
    
    # Benchmark result Home
    url(r'^result/(?P<test_type>.+)', result_views.benchmark_result, name='benchmark_result'),
    
    # cpu usage
    url(r'^usage/cpu$', op_views.get_cpu_usages, name='cpu_usage'),
    url(r'^usage/memory$', op_views.get_memory_usages, name='memory_usage'),
]

vbd/vbd/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from dashboard import views

handler404 = 'dashboard.views.page_not_found'
handler500 = 'dashboard.views.page_error'

urlpatterns = [
    # Examples:
    url(r'^$', views.homepage, name='homepage'),
    url(r'^about$', views.about, name='about'),
    
    url(r'^admin/', include(admin.site.urls)),
    url(r'', include('authen.urls')),
    url(r'', include('dashboard.urls')),
    
    url(r'^captcha/', include('captcha.urls')),
]

vbd/dashboard/models.py
from django.db import models

from dashboard.utility.date_util import get_current_day_start_date

# choices = ['value', 'display name']
CHOICES_PROJECT = [('CVS','CVS'),('ADIS','ADIS'),('MFS','MFS'),('AMFS','AMFS'),]
CHOICES_TYPE = [('VOD_T6', 'VOD_T6'), ('CDVR_T6', 'CDVR_T6'), ('LINEAR_T6', 'LINEAR_T6')]
CHOICES_CONTENT_PREFIX = [('vod_test_', 'vod_test_'), ('t6_test_', 't6_test_'), ('cdvr_hot', 'cdvr_hot'), ('cdvr_fixed', 'cdvr_fixed'), ]

class PerfTestResult(models.Model):
    project_name = models.CharField(max_length=100, choices=CHOICES_PROJECT, blank=False, null=False)
    project_version = models.CharField(max_length=100, blank=False, null=False)
    test_type = models.CharField(max_length=100, choices=CHOICES_TYPE, blank=False, null=False)
    test_date = models.DateTimeField(default=get_current_day_start_date())
    test_config = models.TextField(blank=False, null=False)
    index_summary = models.TextField(blank=False, null=False)
    bitrate_summary = models.TextField(blank=False, null=False)
    error_details = models.TextField(blank=True, null=True)
    instance_number = models.IntegerField(default=2, blank=False, null=False)
    
    def __unicode__(self):
        return '[id:{}, project_name:{}, project_version:{}, test_type:{}, test_date:{}, instance_size:{}]'\
                    .format(self.id, self.project_name, self.project_version, self.test_type, self.test_date.strftime('%Y-%m-%d'), self.instance_number)
    
    def as_dict(self):
        return dict(
            id=self.id,
            project_name=self.project_name,
            project_version=self.project_version,
            test_type=self.test_type,
            test_date=self.test_date.strftime('%Y-%m-%d'),
            test_config=self.test_config,
            index_summary=self.index_summary,
            bitrate_summary=self.bitrate_summary,
            error_details=self.error_details,
            instance_number=self.instance_number,
            )
    
    class Meta:
        db_table = 'perf_result'
        ordering = ['-test_date', '-id']
        get_latest_by = 'test_date'
        unique_together = ("project_name", "project_version", "test_type", "test_date")

def get_test_type_json_list():
    test_type_list = []
    for choice in CHOICES_TYPE:
        test_type_list.append({"id":choice[0], "name":choice[1]})
    return test_type_list

def get_test_project_json_list():
    test_project_list = []
    for choice in CHOICES_PROJECT:
        test_project_list.append({"id":choice[0], "name":choice[1]})
    return test_project_list

def get_test_version_json_list(test_type, project_name=None):
    if project_name is not None:
        result_list = PerfTestResult.objects.filter(project_name=project_name, test_type=test_type).values_list("project_version").distinct()
    else:
        result_list = PerfTestResult.objects.filter(test_type=test_type).values_list("project_version").distinct()
    return [{"id": str(result[0]), "name":str(result[0])} for result in set(result_list)]

def get_test_date_json_list(test_type, project_name=None, project_version=None):
    test_result_list = PerfTestResult.objects.filter(test_type=test_type)
    if project_name is not None:
        test_result_list = test_result_list.filter(project_name=project_name)
    
    if project_version is not None:
        test_result_list = test_result_list.filter(project_version=project_version)
    
    test_result_list = test_result_list.values("id", "test_date").distinct()
    return [{"id": str(result["id"]), "name":result["test_date"].strftime('%m/%d/%Y')} for result in test_result_list]

#-----------------------------------------------------------------#
class PerfTestConfig(models.Model):
    project_name = models.CharField(max_length=100, choices=CHOICES_PROJECT, blank=False, null=False)
    test_type = models.CharField(max_length=100, choices=CHOICES_TYPE, blank=False, null=False)
    test_config = models.TextField(blank=True, null=True)
    
    content_size = models.IntegerField(blank=False, null=False, default=15000)
    bitrate_number = models.IntegerField(blank=False, null=False, default=2)
    
    # To VOD, it is concurrent number. To linear and cdvr, it is total client number.
    session_number = models.IntegerField(blank=True, null=True, default=0)
    warm_up_minute = models.IntegerField(blank=False, null=False, default=0)
    
    content_prefix = models.CharField(max_length=100, choices=CHOICES_CONTENT_PREFIX, blank=False, null=False, default=CHOICES_CONTENT_PREFIX[0][1])
    
    def __unicode__(self):
        return 'id:{}, project_name:{}, test_type:{}, content_size:{}, bitrate_number:{}, session_number:{}, warm_up_minute:{}, content_prefix:{}'\
                    .format(self.id, self.project_name, self.test_type, self.content_size, self.bitrate_number, self.session_number, self.warm_up_minute, self.content_prefix)
    
    class Meta:
        db_table = 'perf_config'
        ordering = ['project_name', ]
        get_latest_by = 'project_name'
        unique_together = ("project_name", "test_type",)

#-----------------------------------------------------------------#
SERVICE_STATUS_TYPE = [('Shell', 'Shell'), ('Http', 'Http')]
SERVICE_STATUS_FLAG = [(True, 'Running'), (False, 'Stopped')]
SERVICE_STATUS_FLAG_DICT = {True:'Running', False: 'Stopped'}

# By default, all the vex component has same version, but also can has its special version 
class VEXVersion(models.Model):
    version = models.CharField(max_length=100, blank=False, null=False, unique=True)
    
    # the default vex version for deployment
    is_default = models.BooleanField(default=True)
    
    def __unicode__(self):
        return 'id:{}, version:{}, is_default:{}'.format(self.id, self.version, self.is_default)
    
    def save(self, force_insert=False, force_update=False, using=None, update_fields=None):
        if self.is_default is True:
            VEXVersion.objects.all().update(is_default=False)
        
        super(VEXVersion, self).save(force_insert, force_update, using, update_fields)
    
    class Meta:
        db_table = 'vex_version'
        ordering = ['version', ]
        get_latest_by = 'version'

class ServiceStatus(models.Model):
    status_cmd = models.CharField(max_length=512, blank=True, null=True)
    status_cmd_type = models.CharField(max_length=100, choices=SERVICE_STATUS_TYPE, blank=False, null=False, default=SERVICE_STATUS_TYPE[-1][0])
    
    # http request timeout
    status_cmd_timeout = models.IntegerField(blank=False, null=False, default=20)
    status_flag = models.BooleanField(choices=SERVICE_STATUS_FLAG, blank=False, null=False, default=SERVICE_STATUS_FLAG[-1][0])
    
    # store the response message from status CMD
    status_response = models.CharField(max_length=2048, blank=True, null=True)
    
    class Meta:
        db_table = 'service_status'
        ordering = ['status_cmd_type', ]
    
    def __unicode__(self):
        return 'id:{}, status:[cmd:{}, cmd_type:{}, cmd_timeout:{}, flag:{}, response:{}]'\
                .format(self.id, self.status_cmd, self.status_cmd_type, self.status_cmd_timeout, self.status_flag, self.status_response)

class OperationGroup(models.Model):
    name = models.CharField(max_length=60, blank=False, null=False, unique=True)
    sort_key = models.IntegerField(blank=False, null=False, unique=True)
    
    class Meta:
        db_table = 'operation_group'
        ordering = ['-sort_key', ]
    
    def __unicode__(self):
        return 'id:{}, name:{}, sore_key:{}'.format(self.id, self.name, self.sort_key)

class BasicOperation(models.Model):
    name = models.CharField(max_length=512, blank=False, null=False)
    start_command = models.CharField(max_length=512, blank=True, null=True)
    stop_command = models.CharField(max_length=512, blank=True, null=True)
    description = models.CharField(max_length=1024, blank=True, null=True)
    status = models.OneToOneField(ServiceStatus, blank=True, null=True)
    command_timeout = models.IntegerField(blank=False, null=False, default=120)
    is_kube_command = models.BooleanField(default=False)
    
    def delete(self, using=None):
        if self.status is not None:
            self.status.delete()
        models.Model.delete(self, using=using)

    class Meta:
        abstract = True
        
    def __unicode__(self):
        return 'id:{}, name:{}, start_command:{}, stop_command:{}, status:{}, is_kube_command:{}'\
                .format(self.id, self.name, self.start_command, self.stop_command, self.status, self.is_kube_command)

class Operation(BasicOperation):
    group = models.ForeignKey(OperationGroup,blank=True, null=True)
    
    class Meta:
        db_table = 'operation'
    
    def __unicode__(self):
        return 'id:{}, name:{}, start_command:{}, stop_command:{}, status:{}, group:{}'\
                .format(self.id, self.name, self.start_command, self.stop_command, self.status, self.group)

class VEXOperation(BasicOperation):
    deploy_command = models.CharField(max_length=512, blank=False, null=False)
    deploy_version = models.ForeignKey(VEXVersion, null=True, blank=True)
    
    # get status info from vex components, parse build info and running version from response of status 
    build_info = models.CharField(max_length=512, blank=True, null=True)
    running_version = models.CharField(max_length=512, blank=True, null=True)
    
    class Meta:
        db_table = 'vex_operation'
        
    def __unicode__(self):
        return 'id:{}, name:{}, start_command:{}, stop_command:{}, status:{}, deploy_command:{}, deploy_version:{}, build_info:{}, running_version'\
                .format(self.id, self.name, self.start_command, self.stop_command, self.status, self.deploy_command, self.deploy_version, self.build_info, self.running_version)

class VEXPerfTestOperation(BasicOperation):
    result_collect_command = models.CharField(max_length=512, blank=True, null=True)

vbd/dashboard/forms.py
from django import forms
from django.forms.models import ModelForm

from dashboard.models import VEXGolbalSettings, KubernetesSettings


class VEXGolbalSettingsFrom(ModelForm):
    class Meta:
        model = VEXGolbalSettings
        fields = '__all__'
    
    grafana_http_address = forms.CharField(max_length=128, help_text=u'Http address of Grafana dashboard. Must be public IP or DNS',
                                           error_messages={'max_length': u'Grafana http address is too long(<128)'})
    
    prometheus_http_address = forms.CharField(max_length=128, help_text=u'Http address of prometheus dashboard. Should be AWS private IP or DNS for the scrapy rate',
                                                     error_messages={'max_length': u'Prometheus http address is too long(<128)'})
    
    use_default_version = forms.BooleanField(help_text=u'Uniform version in VEX deployment', required=False)
    
    def clean_grafana_http_address(self):
        grafana_http_address = self.cleaned_data.get('grafana_http_address')
        if grafana_http_address == '':
            return ''
        
        if grafana_http_address.find('http') != 0:
            raise forms.ValidationError(u'Grafana address should be a http URL')
        return grafana_http_address
    
    def clean_prometheus_http_address(self):
        prometheus_http_address = self.cleaned_data.get('prometheus_http_address')
        if prometheus_http_address == '':
            return ''
        
        if prometheus_http_address.find('http') != 0:
            raise forms.ValidationError(u'Prometheus address should be a http URL')
        return prometheus_http_address

    def clean_use_default_version(self):
        if self.cleaned_data.get('use_default_version') is False:
            return False
        else:
            return True

class KubernetesSettingsFrom(ModelForm):
    class Meta:
        model = KubernetesSettings
        fields = '__all__'
    
    kubectl_ip_address = forms.GenericIPAddressField(max_length=128, help_text=u'Internal IP Address of Kubernete master. Must be AWS private IP or DNS',
                                                     error_messages={'max_length': u'Grafana http address is too long(<128)'})
    kubectl_ssh_key_file = forms.FileField(help_text=u'SSH key file of Kubernete master', error_messages={}, required=True, widget=forms.FileInput())
    
    kubectl_ssh_user = forms.CharField(max_length=128, help_text=u'SSH user Kubernete master',
                                                     error_messages={'max_length': u'User is too long(<128)'})
    
    kubectl_ssh_port = forms.IntegerField(help_text=u'SSH port of Kubernete master',
                                                     error_messages={'max_length': u'port is too long(<128)'})
    
    #def clean_kubectl_ssh_key_file(self):
    #    return self.kubectl_ssh_key_file
        
    

vbd/dashboard/views.py
# -*- coding:utf-8 -*-
import logging
import os

from django.contrib.auth.decorators import login_required
from django.shortcuts import render, render_to_response

from dashboard.forms import VEXGolbalSettingsFrom, KubernetesSettingsFrom
from dashboard.models import VEXGolbalSettings, \
    KubernetesSettings, kube_file_folder
from dashboard.utils import generate_user_context


logger = logging.getLogger(__name__)

# Create your views here.
def homepage(request):
    context = generate_user_context(request)
    return render(request, 'dashboard/homepage.html', context)

def page_not_found(request):
    return render_to_response('404.html')

def page_error(request):
    return render_to_response('500.html')

def about(request):
    context = generate_user_context(request)
    return render(request, 'about.html', context)

@login_required 
def global_settings(request):
    context = generate_user_context(request)
    if request.method == 'POST':
        form = VEXGolbalSettingsFrom(request.POST)
        if form.is_valid():
            VEXGolbalSettings.objects.all().delete()
            form.save()
        
        context['form'] = form
        return render(request, 'dashboard/global_settings.html', context)
    else:
        
        settings = VEXGolbalSettings.objects.all()
        if len(settings) > 0:
            # 给form初始值, 两种方式
            '''
            form = VEXGolbalSettingsFrom(initial={'grafana_http_address': settings[0].grafana_http_address,
                                                  'kubectl_ip_address': settings[0].kubectl_ip_address
                                                  })
            '''
            form = VEXGolbalSettingsFrom(instance = settings[0])
        else:
            form = VEXGolbalSettingsFrom()    
        
        context['form'] = form
        return render(request, 'dashboard/global_settings.html', context)


@login_required 
def kubernetes_settings(request):
    context = generate_user_context(request)
    if request.method == 'POST':
        form = KubernetesSettingsFrom(request.POST, request.FILES)
        if form.is_valid():
            KubernetesSettings.objects.all().delete()
            
            #需要删除原来的key文件, 否则会产生一个加随机数的文件
            from vbd.settings import MEDIA_ROOT
            kube_server_ssh_key_file = MEDIA_ROOT + os.sep + kube_file_folder + os.sep + form.cleaned_data.get('kubectl_ssh_key_file').name
            if os.path.exists(kube_server_ssh_key_file): 
                os.remove(kube_server_ssh_key_file)
            
            form.save()
        context['form'] = form
        return render(request, 'dashboard/kubernetes_settings.html', context)
    else:
        
        settings = KubernetesSettings.objects.all()
        if len(settings) > 0:
            # 给form初始值, 两种方式
            form = KubernetesSettingsFrom(instance = settings[0])
        else:
            form = KubernetesSettingsFrom(initial={'kubectl_ssh_user':'root', 'kubectl_ssh_port':22})    
        
        context['form'] = form
        return render(request, 'dashboard/kubernetes_settings.html', context)

vbd/dashboard/templates/dashboard/homepage.html
{% extends "dashboard-base.html" %}

{% block dashboard-content %}
    <h5>This in homepage content panel</h5>
{% endblock %}

vbd/dashboard/templates/dashboard/kubernetes_settings.html
{% extends "base.html" %}
{% load staticfiles %}
{% block title %}Golbal Settings{% endblock %}

{% block header %}
<script>

var tmp_kubectl_ip_address = "";
var tmp_kubectl_ssh_key_file = "";
var tmp_kubectl_ssh_user = "";
var tmp_kubectl_ssh_port = "";

$(function() {
	{% if form.errors %}
		$("#id_kubectl_ip_address").attr("disabled",false);
		$("#id_kubectl_ssh_key_file").attr("disabled",false);
		$("#id_kubectl_ssh_user").attr("disabled",false);
		$("#id_kubectl_ssh_port").attr("disabled",false);
	
		$("#edit_button").hide();
		$("#save_button").show();
		$("#cancel_button").show();
		
		tmp_kubectl_ip_address = "{{ form.kubectl_ip_address.value }}";
		tmp_kubectl_ssh_key_file = "{{ form.kubectl_ssh_key_file.value }}";
		tmp_kubectl_ssh_user = "{{ form.kubectl_ssh_user.value }}";
		tmp_kubectl_ssh_port = "{{ form.kubectl_ssh_port.value }}";
	{% endif %}
	
	{% if form.kubectl_ssh_port.value %} 
		$("#id_kubectl_ssh_port").attr("checked",true);
	{% endif %}
});

function edit(){
	$("#id_kubectl_ip_address").attr("disabled",false);
	$("#id_kubectl_ssh_key_file").attr("disabled",false);
	$("#id_kubectl_ssh_user").attr("disabled",false);
	$("#id_kubectl_ssh_port").attr("disabled",false);
	
	tmp_kubectl_ip_address = $("#id_kubectl_ip_address").val();
	tmp_kubectl_ssh_key_file = $("#id_kubectl_ssh_key_file").val();
	tmp_kubectl_ssh_user = $("#id_kubectl_ssh_user").val();
	tmp_kubectl_ssh_port = $("#id_kubectl_ssh_port").val();
	
	$("#edit_button").hide();
	$("#save_button").show();
	$("#cancel_button").show();
}

function cancel(){
	$("#id_kubectl_ip_address").val(tmp_kubectl_ip_address);
	$("#id_kubectl_ssh_key_file").val(tmp_kubectl_ssh_key_file);
	$("#id_kubectl_ssh_user").val(tmp_kubectl_ssh_user);
	
	if (tmp_kubectl_ssh_port=="True"){
		$("#id_kubectl_ssh_port").prop("checked", true);
	}else{
		$("#id_kubectl_ssh_port").prop("checked", false);
	}
	
	$("#id_kubectl_ip_address").attr("disabled",true);
	$("#id_kubectl_ssh_key_file").attr("disabled",true);
	$("#id_kubectl_ssh_user").attr("disabled",true);
	$("#id_kubectl_ssh_port").attr("disabled",true);
	
	$("#edit_button").show();
	$("#save_button").hide();
	$("#cancel_button").hide();
}

</script>
{% endblock%}

{% block content %}
<div class="container">
    <div class="row">
        <div class="col-md-10 col-md-offset-1">
            <div class="panel panel-default">
                <div class="panel-heading">
                    <h3 class="panel-title">Kubernetes Server Setting</h3></div>
                <div class="panel-body">
                    <form method="POST" class="form-horizontal" enctype="multipart/form-data">
                        {% csrf_token %}
                        <div class="form-group">
                            <label for="id_kubectl_ip_address_label" class="col-md-3 control-label">{{ form.kubectl_ip_address.label }}</label>
                            <div class="col-md-9">
                                <input type="text" class="form-control" id="id_{{ form.kubectl_ip_address.name }}" name="{{ form.kubectl_ip_address.name }}" autofocus disabled value="{{ form.kubectl_ip_address.value }}">
                                {% if form.errors.kubectl_ip_address %}
                                	<div class="has-warning"><label class="control-label" for="inputWarning"> {{form.errors.kubectl_ip_address}} </label></div>
                                {% else %}
                                	<p class="help-block"> {{form.kubectl_ip_address.help_text}} </p>
                                {% endif %}
                             </div>
                        </div>
                        <div class="form-group">
                            <label for="id_kubectl_ssh_key_file_label" class="col-md-3 control-label">{{ form.kubectl_ssh_key_file.label }}</label>
                            <div class="col-md-9">
                            	<input id="id_{{ form.kubectl_ssh_key_file.name }}" name="{{ form.kubectl_ssh_key_file.name }}" autofocus disabled type="file" class="file" value="{{ form.kubectl_ssh_key_file.value.name }}">
                                {% if form.errors.kubectl_ssh_key_file %}
                                	<div class="has-warning"><label class="control-label" for="inputWarning">{{form.errors.kubectl_ssh_key_file}}</label></div>
                                {% else %}
                                	<p class="help-block">{{form.kubectl_ssh_key_file.help_text}} </p>
                                {% endif %}
                            </div>
                        </div>
                        
                        <div class="form-group">
                            <label for="id_kubectl_ssh_user_label" class="col-md-3 control-label">{{ form.kubectl_ssh_user.label }}</label>
                            <div class="col-md-9">
                            	<input type="text" class="form-control" id="id_{{ form.kubectl_ssh_user.name }}" name="{{ form.kubectl_ssh_user.name }}" autofocus disabled value="{{ form.kubectl_ssh_user.value }}">
                                {% if form.errors.kubectl_ssh_user %}
                                	<div class="has-warning"><label class="control-label" for="inputWarning">{{form.errors.kubectl_ssh_user}}</label></div>
                                {% else %}
                                	<p class="help-block"> {{form.kubectl_ssh_user.help_text}} </p>
                                {% endif %}
                            </div>
                        </div>
                        
                        <div class="form-group">
                            <label for="id_kubectl_ssh_port_label" class="col-md-3 control-label">{{ form.kubectl_ssh_port.label }}</label>
                            <div class="col-md-9">
                            	<input class="form-control" 
                            		id="id_{{ form.kubectl_ssh_port.name }}" name="{{ form.kubectl_ssh_port.name }}" value="{{ form.kubectl_ssh_port.value }}" 
                            		autofocus disabled >
                                {% if form.errors.kubectl_ssh_port %}
                                	<div class="has-warning"><label class="control-label" for="inputWarning">{{form.errors.kubectl_ssh_port}}</label></div>
                                {% else %}
                                	<p class="help-block"> {{form.kubectl_ssh_port.help_text}} </p>
                                {% endif %}
                            </div>
                        </div>
                        
                        <div class="col-md-5 col-md-offset-3">
                            <button type="button" id="edit_button" class="btn btn-success" value="edit" onclick="edit()">Edit</button>
                            <button type="submit" id="save_button" class="btn btn-success" value="save" style="display:none;">Save</button>
                            <button type="button" id="cancel_button" class="btn btn-success" value="cancel" style="display:none;" onclick="cancel()">Cancel</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

vbd/dashboard/templates/dashboard/vod.html
{% extends "dashboard-base.html" %}

{% block dashboard-content %}
    <h5>This in default content panel</h5>
{% endblock %}